// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6SdFKMw1ZhXdJfG_TDjpRQM9PqdwUTcY',
    appId: '1:119692400826:web:3e6a398b8ba23ac1a24a83',
    messagingSenderId: '119692400826',
    projectId: 'viags-vos',
    authDomain: 'viags-vos.firebaseapp.com',
    storageBucket: 'viags-vos.firebasestorage.app',
    measurementId: 'G-1BN6N5FWP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBswIS-A1Ci6ig0yN2oW4xo6oPSZ3aUtuI',
    appId: '1:119692400826:android:d3e9897866b28138a24a83',
    messagingSenderId: '119692400826',
    projectId: 'viags-vos',
    storageBucket: 'viags-vos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx-RK2Xfs6ChbpmgIZylCiNmnCP-zpnuM',
    appId: '1:119692400826:ios:69997882c9bcd259a24a83',
    messagingSenderId: '119692400826',
    projectId: 'viags-vos',
    storageBucket: 'viags-vos.firebasestorage.app',
    iosClientId:
        '119692400826-usibe069lubg2rq3j0lsnn38mobtrso6.apps.googleusercontent.com',
    iosBundleId: 'vn.viags.vos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx-RK2Xfs6ChbpmgIZylCiNmnCP-zpnuM',
    appId: '1:119692400826:ios:2b98cef5df373e91a24a83',
    messagingSenderId: '119692400826',
    projectId: 'viags-vos',
    storageBucket: 'viags-vos.firebasestorage.app',
    iosClientId:
        '119692400826-hben2igt6265ibk1f98ka9uamopcjb3t.apps.googleusercontent.com',
    iosBundleId: 'vn.viags.vos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6SdFKMw1ZhXdJfG_TDjpRQM9PqdwUTcY',
    appId: '1:119692400826:web:10ac891158e858d0a24a83',
    messagingSenderId: '119692400826',
    projectId: 'viags-vos',
    authDomain: 'viags-vos.firebaseapp.com',
    storageBucket: 'viags-vos.firebasestorage.app',
    measurementId: 'G-1GYZRWEXXC',
  );
}
